// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLQUzabQLzJEhhmln38lYQY_Nj0XTKReY',
    appId: '1:748391869538:web:01090815f84b0f54dc753b',
    messagingSenderId: '748391869538',
    projectId: 'test-app-c7b2e',
    authDomain: 'test-app-c7b2e.firebaseapp.com',
    databaseURL: 'https://test-app-c7b2e-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-c7b2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXDAHEb2UyvuDzpQ0hEPPL5eQtbaFo9Vs',
    appId: '1:748391869538:android:071e8530f8696643dc753b',
    messagingSenderId: '748391869538',
    projectId: 'test-app-c7b2e',
    databaseURL: 'https://test-app-c7b2e-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-c7b2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-r6aIDExKUNGcl63FM-CGEFqewrpVZG4',
    appId: '1:748391869538:ios:27f37f2bd3d95a38dc753b',
    messagingSenderId: '748391869538',
    projectId: 'test-app-c7b2e',
    databaseURL: 'https://test-app-c7b2e-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-c7b2e.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-r6aIDExKUNGcl63FM-CGEFqewrpVZG4',
    appId: '1:748391869538:ios:27f37f2bd3d95a38dc753b',
    messagingSenderId: '748391869538',
    projectId: 'test-app-c7b2e',
    databaseURL: 'https://test-app-c7b2e-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-c7b2e.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLQUzabQLzJEhhmln38lYQY_Nj0XTKReY',
    appId: '1:748391869538:web:27673a11a86c6501dc753b',
    messagingSenderId: '748391869538',
    projectId: 'test-app-c7b2e',
    authDomain: 'test-app-c7b2e.firebaseapp.com',
    databaseURL: 'https://test-app-c7b2e-default-rtdb.firebaseio.com',
    storageBucket: 'test-app-c7b2e.firebasestorage.app',
  );

}